name: healthapp
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.1
  get_storage: ^2.0.3
  health: ^3.0.4
  percent_indicator: ^3.4.0
  animated_splash_screen: ^1.2.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/images/footsteps.png
    - assets/images/kcal.png
    - assets/images/boozin.png
    - assets/images/boozindark.png  
  fonts:
     - family: Nunito
       fonts:
          - asset: assets/fonts/Nunito-Bold.ttf
     - family: NunitoSemi
       fonts:
          - asset: assets/fonts/Nunito-SemiBold.ttf


    





